name: Submit dependencies

on:
  push:
    branches:
      - master
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v2
        id: submit
        with:
          configs-ignore: test test-internal

      - name: Print Dependency Snapshot
        run: |
          jq . ${{ steps.submit.outputs.snapshot-json-path }}
