name: Deploy

on:
  push:
    tags:
      - 'v[0-9]*'
      - '!v2[0-9].*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: 'adopt'
    - uses: sbt/setup-sbt@v1
    - name: Publish
      run: |
        printf "[github]\n  actor=${{ secrets.ORG_USERNAME }}\n  token=${{ secrets.ORG_TOKEN }}" > ~/.gitconfig
        sbt +surfaceJVM/publish +surfaceJS/publish
